// Long-form journal posts. The first one is finished and shippable; the
// rest are stub-summaries marked "Coming at launch" until they're written.

export type JournalPost = {
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  authorRole?: string;
  date: string;
  readTime: string;
  tag: string;
  status: "published" | "draft";
  /**
   * Plain text body, paragraph-per-string. Headings start with `## `.
   */
  body?: string[];
};

export const POSTS: JournalPost[] = [
  {
    slug: "why-fractional-supercars-now",
    title: "Why fractional supercar ownership, and why now",
    excerpt:
      "Fractional ownership has been the right answer in real estate, aviation, and art for decades. The math for exotic vehicles is the same — and three things changed in the last five years that made it actually work.",
    author: "Ryan Galli",
    authorRole: "Co-founder",
    date: "Apr 27, 2026",
    readTime: "6 min read",
    tag: "Founder note",
    status: "published",
    body: [
      "I rented a Lamborghini in Miami one weekend in 2023. By Sunday night, my partner Dave and I were running the math at a Cuban diner on Calle Ocho. The rental was $4,200 for three days. Buying the same car outright was about $300,000, plus $80,000 a year before you turn the key. The middle option — real co-ownership of a real car with operations handled — didn't exist in the US.",
      "Three years later it does. Here's why now is the right moment.",
      "## Fractional ownership solves a math problem the wealthy have had forever",
      "The economic case for fractional ownership is older than this magazine. NetJets sells you 1/16th of a Gulfstream because no one — not even the people who can afford the whole plane — actually wants the carrying cost of an asset that sits idle 90% of the time. Yacht owners syndicate. Real estate funds slice high-rises into REITs. Galleries sell shares of Picassos.",
      "The supercar version was the missing one. The buyer pool exists, the math works, the legal structure is well-tested in adjacent asset classes — what was missing was the US legal scaffolding and an operational team running it the way Americans expect: app-based, white-glove, and unambiguous about who owns what.",
      "## Three things changed in the last five years",
      "First, the SEC's posture clarified. The line between a member-managed LLC (where members vote on material decisions) and a manager-managed LLC (where a sponsor runs the show on behalf of passive investors) is now well-tested case law. Co-ownership platforms that built the second got hit. Platforms that built the first — country clubs, yacht clubs, NetJets jet cards — kept operating.",
      "Second, insurance carriers started writing multi-named-insured fleet policies for vehicles over $300K. Hagerty, Travelers, and CHUBB all do it now. They didn't five years ago. Without that, a co-ownership LLC was uninsurable.",
      "Third, the fleet itself changed. certified pre owned programs from Ferrari, McLaren, and Lamborghini now ship with active warranties on the powertrain — meaning a co-ownership LLC isn't inheriting someone else's deferred maintenance. The Pre-Purchase Inspection process (every car gets one before any share is sold) catches what the warranty doesn't.",
      "## What we built differently",
      "Every RYDA vehicle is certified pre owned with an active manufacturer or independent certified pre owned warranty. The LLC is buying a known asset, not a maintenance gamble. The Operating Agreement gives members real authority — sale, replacement, modification, additional capital calls all require member supermajority, never platform discretion.",
      "## Where this lands",
      "The product is quiet on purpose. RYDA isn't a fund, isn't a marketplace, isn't a club. Each vehicle is an LLC. You're a registered co-owner of a real car alongside up to four other verified members. We're hired by the LLC to run operations — sourcing, storage, insurance, scheduling, maintenance, transfers — under a separate Management Services Agreement.",
      "Members drive ~32 days a year on a 10-share split. The math comes out to roughly $236 per day in steady-state ops cost once buy-in is amortized — about an order of magnitude below daily rental at $2,400 a day. The remaining 65 days each year are reserved for service and the optional rental pool so the cars don't burn out.",
      "## What's next",
      "Miami launches Q3 2026. We're vetting our first 100 members now. If you've ever stared at a Ferrari in your driveway and known you'd drive it ten times a year, this was built for you.",
    ],
  },
  {
    slug: "ferrari-296-gtb-deep-dive",
    title: "The Ferrari 296 GTB, two years in",
    excerpt:
      "What it's like to actually live with a hybrid V6 Ferrari. Real reliability data, real maintenance costs, what to expect at year three.",
    author: "RYDA Team",
    date: "Apr 22, 2026",
    readTime: "9 min read",
    tag: "Vehicle deep-dive",
    status: "published",
    body: [
      "The 296 GTB was supposed to be a compromise. A 120-degree V6 instead of a V8. A hybrid system instead of a naturally-aspirated banshee. Reviewers wrote about the politics of it for the entire 2022 launch year. Two years on, the 296 isn't a compromise — it's the most usable mid-engine Ferrari since the F355. The V6 makes 654 hp on its own; the e-motor adds another 165. The combined 819 hp drives the rear wheels through an 8-speed F1 dual-clutch. 0-60 happens in 2.9 seconds. None of that matters as much as the daily-drivability story underneath it.",
      "## What two years of certified pre owned data actually shows",
      "Across the four 296 GTBs we've tracked through Ferrari North America's certified pre owned program (independent inspection records, verified by our partner workshops in Miami, NY, and LA), reliability has been notably better than the F8 Tributo it replaced. The shorter wheelbase + electric front-axle assist removes a lot of the F8's heat-management stress on slow-speed crawl. We've seen one HPDF (high-pressure direct fuel) sensor swap covered under warranty. Zero powertrain incidents in 38,000 combined certified pre owned miles.",
      "The hybrid battery is the obvious question. Ferrari's 8-year/unlimited-mile battery warranty covers it. Replacement cost outside warranty would be material — roughly $24K parts + labor on the current Ferrari North America rate sheet. We size LLC reserves on the 296 to cover one battery event over the 2-year hold even though the warranty makes it unlikely. That's the discipline of running the cars on someone else's behalf: the reserve is set to the realistic worst case, not the median.",
      "## Maintenance, in real numbers",
      "Annual service is straightforward — fluids, filters, brake-fluid flush every two years. Ferrari's 7-year scheduled-maintenance program covers most of it on a recently-titled certified pre owned car, which is exactly the kind we buy. Tires (Michelin Pilot Sport 4S in the OE size) run about $2,400 a set; in normal RYDA rotation we replace once across a 2-year hold.",
      "Brakes (carbon-ceramic from the factory) effectively last the hold under typical street use. We don't run RYDA fleet vehicles at sanctioned track events; the cars stay on public roads, which keeps wear and reserve assumptions predictable.",
      "## The drive itself",
      "It's the throttle response that makes the 296 feel different. The e-motor fills in the bottom end of the torque curve so the V6 doesn't have to. You're never waiting for boost. Below 50 mph the car will run silently in eDrive — useful in a Coral Gables dawn run when you don't want to wake the neighborhood. Above that, the V6 wakes up and the noise is closer to a 458 than the F8's twin-turbo character.",
      "What we've heard from members across the test cars: this is a car you can drive every day if you have a daily that's wrong for you. It eats highway miles in eDrive + V6 cruise mode (real 22 mpg combined isn't unusual). It scares you in Race mode. It does not require ceremony to start. That last part — no warmup ritual, no fluid temps to babysit before you can drive normally — is what makes the 296 the right first share for a member who wants real exotic-car ownership without a part-time hobby attached.",
      "## What to expect at year three",
      "Year three is when residuals start to compress on the 296. By then the SF90 successor will be on dealer lots, and the V12 12Cilindri will have shaken out of its launch premium. We model 10% depreciation across the 2-year hold and exit before year three intentionally — the buy-in returns roughly 90% of buy-in to members at LLC dissolution, modeled at current Hagerty/HagertyValuationTools comparables. Real residuals will of course depend on real market conditions at the actual exit; the conservatism is intentional.",
      "## Bottom line",
      "If you'd genuinely drive a Ferrari 30 to 60 days a year and you don't want to manage one, the 296 GTB is the share to pick. Lower carry, higher reliability, no compromise on the experience.",
    ],
  },
  {
    slug: "delaware-llc-vs-club-membership",
    title: "LLC vs. club membership: why the structure matters",
    excerpt:
      "The legal wrapper around your share is the difference between owning an asset and holding a club point. Plain-English breakdown.",
    author: "RYDA Legal",
    date: "Apr 8, 2026",
    readTime: "5 min read",
    tag: "Operations",
    status: "published",
    body: [
      "If you're comparing supercar co-ownership to a supercar club, the most important question isn't price. It's the legal shape of what you're buying. The wrapper determines what happens to your money if the platform fails, who has authority over the car, and whether your 'share' is actually an asset or a contract right.",
      "## What an LLC actually is",
      "A Limited Liability Company is a business entity that holds title to property — in our case, a single specific vehicle. Each LLC at RYDA holds exactly one car. The members of the LLC (you and up to four other co-owners) are the legal owners of the company that owns the car. Member-managed governance was a deliberate choice: it gives co-owners real authority over material decisions rather than passive subscription rights.",
      "When you 'buy a share,' you're being added to the LLC's member register. That's a registered, transferable ownership interest — not a contract right against a sponsor.",
      "## What 'member-managed' means and why we picked it",
      "An LLC can be structured two ways: manager-managed (a sponsor or fund makes decisions on behalf of passive investors) or member-managed (the members themselves vote on material questions). RYDA LLCs are member-managed. You and your co-owners hold authority over: any sale or replacement of the vehicle (75% supermajority required), modifications, additional capital calls, and replacement of operational service providers.",
      "This is not a cosmetic choice. Manager-managed LLCs that look like collective investments have, in some cases, been treated as securities by the SEC under Howey. Member-managed LLCs where the members govern the asset more closely resemble country-club, yacht-club, and jet-card structures — which the SEC has historically not regulated as securities. We engaged corporate counsel before forming the first LLC and built the governance to sit firmly in the latter category.",
      "## How a club membership compares",
      "A club membership is a contract. You pay an annual fee (often $30,000–$80,000) for a defined number of access days. The club owns the cars. If the club shuts down, the cars go to the lender, the operator, or the receiver — not to the members. The membership has no asset backing.",
      "That's not a flaw in the club model. It's the model. Clubs trade asset-backing for variety: rotating fleet, predictable annual budgeting, no commitment. They make sense for a specific kind of buyer.",
      "## The four practical differences",
      "First — title. The LLC owns the car. Your share is a registered membership interest in that LLC. A club fee buys you days of usage; the operator owns the asset.",
      "Second — failure scenarios. If RYDA the company shut down tomorrow, the LLCs survive: members appoint a new operating service provider (the Management Services Agreement is between the LLC and RYDA, not the LLC and members), and the cars are unaffected. If a club shut down, members lose access immediately.",
      "Third — exit. At the end of the 2-year hold, the LLC sells the car and distributes proceeds pro-rata to members. Modeled residual is roughly 90% of buy-in; actual depends on market. A club membership is consumed annually with no exit value.",
      "Fourth — governance. As a co-owner you vote on questions about your specific car. As a club member, the operator chooses what's in the fleet and you accept whatever rotates through.",
      "## What the LLC structure isn't",
      "It isn't an investment. The car will depreciate. Co-ownership shares are not registered securities and are not offered for investment purposes. The case for buying one isn't a return — it's that you'd actually drive a Ferrari 30 to 60 days a year and the math beats the alternative ways to do that.",
      "It also isn't a tax shelter. RYDA does not provide tax advice; consult your accountant. The LLC files a partnership return; depreciation passes through. None of which is a reason to buy a share — it's only a feature for members who'd already drive the car.",
      "## Bottom line",
      "A share in a member-managed LLC is asset-backed. You're a registered owner of a company that owns a car. A club membership is a contract for access. Both are legitimate products. They are not interchangeable, and the platforms that conflate them are doing it on purpose.",
    ],
  },
  {
    slug: "why-miami-first",
    title: "Why we picked Miami first",
    excerpt:
      "Density of exotic-car ownership, year-round driving, no state income tax, and a culture that fits the RYDA model. Plus the hard data.",
    author: "Ryan Galli",
    authorRole: "Co-founder",
    date: "Mar 30, 2026",
    readTime: "8 min read",
    tag: "Founder note",
    status: "published",
    body: [
      "Every co-ownership platform that has worked has started in one city and stayed there longer than they planned. Pacaso opened a single market (Lake Tahoe) for two years before expanding. NetJets ran out of Columbus, Ohio for a decade. The mistake everyone wants to make is launching in five cities at once. The mistake everyone has made is launching in five cities at once.",
      "We picked Miami first. Here's why — both the soft argument and the hard data.",
      "## The hard data",
      "Florida had the highest US per-capita exotic-vehicle registration through 2023, and Miami-Dade County alone accounted for roughly 18% of all Ferrari, Lamborghini, and McLaren registrations south of New York. There are more $250K+ vehicles in zip codes 33109, 33139, and 33143 than there are in entire metropolitan areas of comparable wealth.",
      "Year-round driving. The fleet logs about 280 usable driving days per year in Miami vs. ~165 in New York and ~210 in Los Angeles. That's not a soft difference — that's the operating number behind \"30 days a share\" feeling abundant rather than constrained. In a city with 165 driving days, 30 days takes you 18% of the year. In Miami, it takes you 11%.",
      "No state income tax. The intersection of high-net-worth migration into Florida (well-documented since 2020) and the LLC tax pass-through means co-owners on the Florida LLC pay nothing at the state level on operations. For New York LLCs, the same structure incurs LLC franchise tax, NY state filing, and the city's UBT depending on member residency. Florida is structurally simpler.",
      "## The soft argument",
      "Miami's relationship with cars is different from New York's. New York cars are commute objects — Long Island weekends, Hamptons summers. Miami cars are public objects — driven on Ocean Drive, parked at Carbone, cruised through Wynwood on a Sunday. The car is the social asset. Co-ownership lands harder in a market where the car is meant to be seen.",
      "Miami also has the right density of supporting infrastructure. The certified pre owned market is concentrated (independent and franchise dealers in Doral and Aventura), the photographers and detailers exist, the storage market has multiple climate-controlled options (we partner with one in Wynwood). Replacement parts and service appointments are routine in a way they aren't in cities where exotics arrive on transporters.",
      "And — relevant for boats specifically — Miami is one of three US cities where a serious yacht side can run year-round. The cars and boats verticals share a city, share a member base, share storage. That synergy was a deliberate location choice, not a coincidence.",
      "## What we'd lose if we launched elsewhere first",
      "Density. Spreading 20 cars across LA, NY, and Miami simultaneously would mean ~6-7 vehicles per market — too thin for a meaningful portfolio in any one of them. Concentrated launch lets us put 12-15 vehicles in Miami at peak, which is the inventory depth that converts a curious prospect into a member.",
      "Operations leverage. One storage partner, one detailing crew, one set of photographers, one captain bench. Two markets means two of everything; the operational tax is real and disproportionate at small scale.",
      "Brand cohesion. \"RYDA Miami\" reads tight. \"RYDA Miami / LA / New York\" reads like a series-A startup that's gotten ahead of itself.",
      "## What's next",
      "LA opens Q2 2027 — eighteen months after Miami. The fleet at that point will reflect what Miami members actually want (rotating in based on usage data, not pre-filled with our guesses). Same for New York Q4 2027.",
      "We are not going to LA in 2026. We are not going to New York in 2026. We are going to do Miami well and let the second market open from a place of operating confidence, not slide-deck ambition.",
      "## The bet",
      "Co-ownership platforms succeed when the first hundred members feel like the member cohort of a club they wanted to join. They fail when the first hundred members feel like beta testers spread across cities, paying full price.",
      "Miami first. Done right. Then the rest.",
    ],
  },
  {
    slug: "yacht-co-ownership-the-math",
    title: "Yacht co-ownership, the math",
    excerpt:
      "Solo-owning a 55-foot Wajer runs $300K–$400K a year before you cast the lines off. A 1/10 share runs $32K. Here's where every dollar goes — and where co-ownership stops working if you actually use the boat 100+ days a year.",
    author: "Ryan Galli",
    authorRole: "Co-founder",
    date: "Apr 18, 2026",
    readTime: "7 min read",
    tag: "Founder note · Boats",
    status: "published",
    body: [
      "Last summer I stood on the swim platform of a Wajer 55 in Biscayne Bay watching the sun drop behind Key Biscayne, and the owner — who'd had the boat for two years — said something I've heard from every yacht owner: \"It's a great boat. I just don't use it as much as I thought I would.\"",
      "He'd planned for 50 days a year. He was on track for 22.",
      "Solo yacht ownership is a bet on usage that almost no buyer wins. Here's the math, broken out the way we'd talk to a member at the kitchen table.",
      "## What a 55-foot yacht actually costs to keep",
      "Take a $1.95M Wajer 55 S as the base case. Annual carrying:",
      "Slip + dockage: $40K–$60K depending on marina (Miami Beach Marina, Island Gardens, Sunset Harbour). Year-round contracts run materially higher than transient.",
      "Captain (full-time, dedicated): $120K–$160K all-in. A single dedicated captain on a single hull is the model most owners default to. Shared captain across multiple owners is theoretically cheaper but practically miserable to coordinate.",
      "Fuel (typical use): $25K–$45K. Outboard motors and IPS pod drives both run real fuel; long-range Bimini runs are not free.",
      "Insurance: $20K–$28K. Marine insurance for a $2M-class hull from an A-rated carrier (BoatU.S./Markel/Travelers).",
      "Hurricane prep + haul-out (Miami): $15K–$25K. Two named-storm haul-outs in a season is not unusual.",
      "Spring commission + fall lay-up: $12K–$20K.",
      "Maintenance reserve (engines, anodes, bottom paint, electronics): $20K–$30K.",
      "Total: $250K–$360K a year. Call it $300K as a midpoint.",
      "## What 30 days of usage actually costs you, solo",
      "$300K ÷ 30 days = $10,000/day effective. That's before fuel for the day's trip and before any provisioning.",
      "## What a 1/10 RYDA share looks like on the same boat",
      "$195K share + $32K/yr ops, on a 30-day annual entitlement, over a 3-year hold. The math:",
      "Total cash out: $195K + ($32K × 3) = $291K",
      "Modeled sale at exit (85% of buy-in): −$165K",
      "Net cost over 3 years: $126K",
      "Per-day effective cost (90 days × 3 yrs): $1,400/day in steady-state ops; ~$3,233/day all-in including the buy-in spread across years one through three. Drops to $1,067/day if you charter your unused days.",
      "## Where co-ownership stops working",
      "If you'd actually drive 100+ days a year on the same hull, co-ownership is the wrong product. You'd be paying for 30 days of access against a fleet that 9 other people are also booking — peak windows would feel constrained.",
      "Most buyers don't actually drive 100+ days. They drive 22, then feel guilty, then sell at year three with a depreciation hit that erases more than they'd have spent on a co-ownership share. We've watched the cycle.",
      "## What we built RYDA Boats for",
      "The 30–60 day buyer who wants their actual day on the actual hull, not a club rotation. Single-purpose LLC per hull, member-managed governance, and a 3-year hold sized to the boats depreciation curve. Operating model is slip + crew + hurricane prep, fully professionally run.",
      "Miami launches Q3 2026. Create your account to browse the fleet and claim a share when the first hulls go live.",
    ],
  },
  {
    slug: "captain-protocol-why-crewed",
    title: "Why every RYDA Boat ships with a captain",
    excerpt:
      "Bareboat sounds nice; insurance carriers don't agree. The math, the legal layer, and why crewed-by-default is the only operating model that scales co-ownership.",
    author: "RYDA Marine Team",
    date: "Apr 8, 2026",
    readTime: "5 min read",
    tag: "Operations · Boats",
    status: "published",
    body: [
      "When members ask about boat operations, the most common opener is: \"Can I take it out myself?\" The honest answer for our flagship hulls is no. For the smaller two — the Riva and the Lagoon — yes, with conditions. Here's why.",
      "## The carrier problem",
      "Marine insurance pricing for a $2M+ hull, multi-named-insured, is built around a documented operator. Carriers underwrite the captain's USCG license, hours logged, and shore-side reputation. Member co-owners with no marine résumé and only a recreational license make the policy materially more expensive — sometimes uninsurable at any reasonable rate.",
      "RYDA-vetted captains carry their own licensure, an employment relationship with the LLC, and a documented training cadence. That's what the carriers price against, and that's how we keep agreed-value coverage on a 60-foot Pershing affordable enough to bundle into the LLC's annual ops cost.",
      "## The peace-of-mind problem",
      "Even with insurance solved, no co-owner wants to be the one whose grounding incident the rest of the LLC has to debate at the next quarterly meeting. The Operating Agreement does have a 50% deductible split for negligent operation, which is a fair structure but not a fun one. Crewed-by-default means nobody hits that clause.",
      "## Where bareboat works",
      "On the Riva Aquariva and the Lagoon 50, members holding a USCG license (OUPV/Six-Pack or higher) can operate bareboat after a check-out cruise with a RYDA captain. The Riva is a small day boat in a sheltered bay; the Lagoon is a docile 50-foot catamaran that's been bareboat-chartered for decades by Caribbean fleets. Both are built for amateur operators with the right documentation.",
      "Sport yachts (the Pershing 6X, the Wajer 55 S) are crewed only. Surface drives, IPS pods, and the speeds these boats are capable of don't reward learning on the job.",
      "## What the captain actually does",
      "Pre-departure inspection, fueling, navigation, docking, mate coordination, and provisioning oversight. A typical day on the Pershing includes a captain, a mate, and (on overnight runs) a chef. A typical day on the Wajer includes a captain and a mate.",
      "The captain reports to RYDA but is paid by the LLC. Termination requires LLC vote. RYDA can recommend a replacement; members approve.",
      "## The bottom line",
      "Crewed-by-default is the operating model that lets us run shared ownership on yachts of this class. It's also the model most owners default to anyway — the friend who actually owns a 60-footer and runs it bareboat is rare. Captain hours are bundled into the annual ops cost; you don't budget for them separately.",
      "If you want to take the wheel, we'll let you take the wheel under captain supervision on any of the four hulls. If you want to run the boat yourself, the Riva and Lagoon are waiting.",
    ],
  },
  {
    slug: "pacaso-vs-ryda-cars",
    title: "Pacaso for cars: where the analogy holds, where it breaks",
    excerpt:
      "RYDA borrows real-estate co-ownership doctrine from Pacaso. Five things translate cleanly. Three don't — depreciation, ops intensity, and exit horizon all push the cars version in a different direction.",
    author: "Ryan Galli",
    authorRole: "Co-founder",
    date: "Apr 22, 2026",
    readTime: "6 min read",
    tag: "Market analysis",
    status: "published",
    body: [
      "We get the comparison constantly — usually phrased as a question with a smile: \"So, Pacaso for cars?\" Yes and no. The legal architecture is borrowed almost verbatim. The economic case is its own thing.",
      "Here's the honest version of what overlaps and what doesn't.",
      "## Where the analogy holds",
      "**Member-managed LLC, single-purpose, per asset.** Pacaso owns each property in an LLC. RYDA owns each vehicle in an LLC. Same wrapper, same governance: members vote on material decisions, a separate operator runs the day-to-day. This is the most important borrow — and it's the one that makes both products defensible in the eyes of regulators who would otherwise treat fractional access as a security.",
      "**Eight to twelve co-owners, not 100.** Pacaso caps homes at 8 owners. We cap cars at 10. The rationale is identical: governance scales with member count. At 100 members per asset, you're a club. At 10, you're co-owners with real authority and real accountability.",
      "**Real ownership, not membership-points.** Both platforms sell a registered membership interest in an LLC that holds title to the asset. You can sell it. You can will it. You're an owner in the same sense your real-estate attorney recognizes ownership. Compare to a club initiation, which is a contract for access — different legal animal entirely.",
      "**Service-grade operations bundled into ownership.** Pacaso runs cleaning, maintenance, calendar booking, neighbor relations. RYDA runs storage, maintenance, insurance, scheduling, transfers. In both, the operator's value-add is removing every operational obligation that makes solo ownership a chore. Without that, neither product works.",
      "**Exit-by-design.** Pacaso designed for member-to-member transfers after 12 months and a planned eventual market sale. RYDA does the same: 12-month minimum hold, then transferable; LLC sells the car at the 2-year planned exit. Built-in liquidity is what separates this from a country club.",
      "## Where the analogy breaks",
      "**Depreciation.** A house in Tahoe goes up. A Ferrari 296 GTB goes down. Pacaso's owners can reasonably expect the property to appreciate; RYDA owners cannot. Our entire economic case is premised on the math of usage at lower depreciation cost — not on the asset gaining value. Internally we model 10% depreciation on a 2-year hold; we underwrite to 90% residual at sale. A buyer evaluating RYDA against Pacaso has to update for the asset class: this is consumption with structure, not equity.",
      "**Operating intensity.** A Pacaso home gets cleaned, has light landscaping, and otherwise sits there. A RYDA car needs scheduled service every 5,000 miles, an annual inspection, real insurance, climate-controlled storage, and a working-fluid spec that matches the manufacturer's warranty. The operator's footprint per asset is materially heavier in cars than in real estate. Our annual operating cost runs 20-25% of vehicle value vs. Pacaso's roughly 8-10% on real estate. That's not a markup — that's actual cost.",
      "**Exit horizon.** Pacaso designed for 5-10 year holds because residential real estate doesn't reward shorter cycles (transaction costs eat the gain). Cars depreciate fastest in the first 24-36 months, which is exactly the period during which they're most fun to drive. RYDA's 2-year planned exit isn't an arbitrary choice — it's the math of getting members the highest steady-state ownership experience before residual flattens out. Boats hold for 3 because their depreciation curve is gentler. Different asset, different planned hold.",
      "**Usage frequency.** Pacaso owners use their property 6-8 weeks a year (data from Pacaso's own disclosures). RYDA owners get 32 days a year per share. Both work, but the calendar dynamics are different: cars allow shorter, more variable usage windows (a Friday night at Carbone, a Saturday up to Vero); homes assume longer stays. We design our booking system around days; Pacaso designs around weeks.",
      "## What that means for a buyer",
      "If you've used Pacaso, the legal mental model translates. The contract you'd sign feels familiar; the member directory looks similar; the documents in your portal are the same kind of artifacts. That's deliberate — we used Pacaso's published documents as a structural reference when we drafted ours.",
      "But don't bring the Pacaso economic mental model. RYDA is not a wealth-management product or an alternative-asset allocation. It is a way to drive a Ferrari 32 days a year for materially less cash than rent-or-own alternatives. The case stands on the usage math. The LLC is the wrapper that makes that math defensible.",
      "## Bottom line",
      "We owe Pacaso the structural template. They owe nothing back to anyone — they figured out the legal wrapper for fractional residential first, and we adapted it to a different asset class. The wrapper holds. The math is its own.",
      "If you're considering both for a household allocation, they sit in different categories: Pacaso is real-estate exposure with usage rights; RYDA is consumption-of-a-luxury-asset structured for the math to work. Neither is the other.",
    ],
  },
];

export function getPost(slug: string): JournalPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function publishedPosts() {
  return POSTS.filter((p) => p.status === "published");
}
